
name: Merge CI
on: [ pull_request ]
jobs:
  Test: 
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [ masos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - run: python main.py 